### ISSUE TITLE
The design choices regarding 

### ISSUE THREAD

**Issue by vwxyzjn** [cpnota/autonomous-learning-library#141]
Hi @cpnota, thanks for the great work, I found it to be a very high-quality reference implementation. There is something the caught my attention when I went through the documentation though. Specifically, the design of the agents' interface is 

```python
class Agent(ABC):
    @abstractmethod
    def act(self, state, reward):
        pass

    @abstractmethod
    def eval(self, state, reward):
        pass
```

But why does the `act` method require a reward to be passed? My understanding is that the agent only receives a reward once the action has been commited and then the env returns a reward. Would love to hear the reasons behind your design choices.

**Comment by cpnota** [comment]
Hi @vwxyzjn, great question!

The short answer is that this is the standard interface for an RL agent as found in the Sutton and Barto ([image](https://autonomous-learning-library.readthedocs.io/en/stable/_images/rl.jpg)). And indeed, this matches the normal use case:

```python
while True:
    action = agent.act(env.state, env.reward)
    env.step(action)
```

Recall the env.reward is the reward for the *previous* action.
This *could* in premise be separated into two steps, e.g.:

```python
while True:
    action = agent.act(env.state)
    reward = env.step(action)
    agent.reinforce(env.reward)
```

However, we have then introduced a [temporal coupling](https://blog.ploeh.dk/2011/05/24/DesignSmellTemporalCoupling/), e.g., we could break our agent by calling functions out of order:

```Python
while True:
    action = agent.act(env.state)
    env.step(action)
    action = agent.act(env.state)
    agent.reinforce(env.reward)
```

Is this behavior well-defined? Will our code raise an exception? We avoid the problem altogether if we pass state and reward together. As long as we only pass valid states and valid rewards, even out of order, an Agent should work as expected.

As for why `.eval(state, reward)` accepts a reward in addition to the state, this is because in premise, the policy may depend on the reward. While we have no such examples implemented, this is seen in some recurrent architectures, as well as some meta-RL work. We wanted to ensure that we did not need to change the interface later.
