### ISSUE TITLE
CUDA: out of memory

### ISSUE THREAD

**Issue by vwxyzjn** [cpnota/autonomous-learning-library#144]
Hi, thanks for the great library. I had a issue with using GPU training the agents to play Breakout. 

Here is the file that runs the https://github.com/vwxyzjn/autonomous-learning-library/blob/master/examples/atari_exp.py

In particular, the GPU memory of 15.90 GiB runs out, which seems like a bug

![image](https://user-images.githubusercontent.com/5555347/82387744-dbb7ef00-9a05-11ea-822b-6336bf565404.png)

**Comment by cpnota** [comment]
Ah, looks like this is happening because you're applying the lazy frame optimization *before* `AtariExperiment` converts the state to a Pytorch tensor, which means that it ends up storing the same frames in memory over and over. In some libraries, they just store the numpy array, which is what the OpenAI wrappers assume. We instead convert it to a `tensor` first so that we don't have to transfer the frame to GPU every time.

Notice that in the original version of the library, we apply `FrameStack` as a `Body` wrapper around the `Agent`, and this is where the lazy frame occurs. You could accomplish the same by making some tweaks to `Atari2Environment`, or by removing `FrameStack(Wrapper)` from the wrappers you use and using the `FrameStack(Body)`. Either way, they key is that lazy frame optimization needs to be applied to the *tensor* representing the state, not the numpy array. (You could also just change the replay buffer size to 500,000).

**Comment by vwxyzjn** [comment]
Thanks for the prompt reply. I will give it a try. I would say even with that optimization, it seems the GPU usage is still huge. Is it mainly because the replay buffer will exist in GPU memory? For example, when running on my own 6GB GPU using the presets, the GPU would still run out of memory. As an example, see 

https://app.wandb.ai/cleanrl/cleanRL/runs/ulynx7uy/code?workspace=user-costa-huang
![image](https://user-images.githubusercontent.com/5555347/82389143-5f270f80-9a09-11ea-9537-fb1b874b4e85.png)



The reason that I am using the original wrapper is that I realized the original wrapper resets the environment once the life is lost, however, in your implementation, it seems you just mark the state as terminal and continue with the state the has one less life. Because of this difference I wanted to examine if my implementation would produce similar results as yours when we use the same environment.

**Comment by cpnota** [comment]
There's no helping it unfortunately. Consider, each frame is an 84x84 image with each pixel represented by a byte. If we store 1 million frames in memory, this means the total size of the replay buffer is at least `84x84x1000000 = 7 GB`, approximately. In practice, I found on my 8 GB card I could still only store around 850k frames before running out of memory due to additional overhead from Pytorch.

**Comment by vwxyzjn** [comment]
I understand. Thanks a lot.

**Comment by mctigger** [comment]
@cpnota Do I understand correctly, that the ReplayBuffer is intended to store either on GPU oder CPU? So if I want to have the replay buffer on the CPU and transfer to the GPU on the fly I would have to modify the `sample()` method?
