### ISSUE TITLE
Motivation behind `nn.Linear0`

### ISSUE THREAD

**Issue by vwxyzjn** [cpnota/autonomous-learning-library#153]
Hi, in a lot of the preset models, I saw the use of `nn.Linear0` layer, whiuch initialize the weights and biases to be zero. I have never seen such initialization technique. the initialization technique I have seen is usually orthogonal initialization with different scale. If you do not mind, could you elaborate your justification on its usage? Furthermore, have you had experiments that suggest the usageof `nn.Linear0` is important compared to just using a vanilla `nn.Linear`?

Thanks.

**Comment by cpnota** [comment]
It helps a little. Note that we only use `Linear0` on the output layer. For value-based agents, this stabilizes some of the early updates. For agents with stochastic policies, this ensures that the initial action distribution is uniformly random, rather than biased (or for Gaussian policies, that the mean is zero). Mostly, it decrease the likelihood of getting a bad initialization. There were some similar findings published recently: https://arxiv.org/abs/2006.05990
